# Generated by Django 4.2.10 on 2024-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_track_track_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='track_list',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='main_app.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='thumbnail_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
