# Generated by Django 4.2.10 on 2024-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_title_playlist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlists', to='main_app.track'),
        ),
    ]
